<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Privacy Policy - Tadafuq</title>
    <style>
        body{
            padding: 0;
            margin: 0;
            box-sizing: border-box;
            overflow-x: hidden;
        }
        nav{
            width: 100%;
            height: 100px;
            padding: 0 5%;
            display: flex;
            align-items: center;
        }
        nav img{
            width: 80px;
            height: 80px;
        }
        .privacy-content{
            width: 90%;
            margin: auto;
            padding: 20px 0;
        }
        @media(max-width:767px){
            .privacy-content h1{
                font-size: 25px;
            }
            .privacy-content h2{
                font-size: 20px;
            }
        }
    </style>
</head>

<body>
    <nav>
        <img src="{{asset('dashboard/assets2.png')}}" loading="lazy" alt="logo" />
    </nav>
    <div class="privacy-content">
        <h1>Privacy Policy for Tadafuq</h1>
        <p>Last updated: November 14, 2024</p>

        <h2>Privacy Policy</h2>
        <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your
            information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>
        <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the
            collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been
            created with the help of the Free Privacy Policy Generator.</p>

        <h3>Interpretation and Definitions</h3>

        <h4>Interpretation</h4>
        <p>The words of which the initial letter is capitalized have meanings defined under the following conditions.
            The following definitions shall have the same meaning regardless of whether they appear in singular or in
            plural.</p>

        <h4>Definitions</h4>
        <p>For the purposes of this Privacy Policy:</p>
        <ul>
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our
                Service.</li>
            <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control
                with a party, where "control" means ownership of 50% or more of the shares, equity interest or other
                securities entitled to vote for election of directors or other managing authority.</li>
            <li><strong>Application</strong> refers to Tadafuq, the software program provided by the Company.</li>
            <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement)
                refers to Tadafuq.</li>
            <li><strong>Country</strong> refers to: Egypt</li>
            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or
                a digital tablet.</li>
            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable
                individual.</li>
            <li><strong>Service</strong> refers to the Application.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of
                the Company. It refers to third-party companies or individuals employed by the Company to facilitate the
                Service, to provide the Service on behalf of the Company, to perform services related to the Service or
                to assist the Company in analyzing how the Service is used.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the
                Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal
                entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
        </ul>

        <h2>Collecting and Using Your Personal Data</h2>

        <h3>Types of Data Collected</h3>

        <h4>Personal Data</h4>
        <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that
            can be used to contact or identify You. Personally identifiable information may include, but is not limited
            to:</p>
        <ul>
            <li>Email address</li>
            <li>Usage Data</li>
        </ul>

        <h2>Human Resources Flow Privacy Information</h2>
        <p>We are in Human Resources Flow, especially for employees. We respect your privacy and are committed to
            protecting your personal data. This privacy policy explains how we collect, use, and protect your data when
            you use our app.</p>

        <h3>1. Information We Collect</h3>
        <ul>
            <li><strong>Personal Information:</strong> When logging into the app, we collect the username and password
                registered by the administrator (admin).</li>
            <li><strong>Attendance and Absence Information:</strong> We record your attendance and absence times when
                you log in and use app functions such as "Register Attendance" and "Submit Requests".</li>
            <li><strong>Leave and Permission Information:</strong> We store data about leave and permission requests
                that you submit through the app.</li>
        </ul>

        <h3>2. How We Use the Data</h3>
        <ul>
            <li><strong>Attendance Registration:</strong> Attendance data is used to document the timing of attendance
                and absence and monitor overall attendance.</li>
            <li><strong>Leave and Permissions:</strong> Data from requests are used to review and document the leaves
                and permissions submitted by users.</li>
            <li><strong>App Improvement:</strong> We may use data to enhance app functions and user experience.</li>
        </ul>

        <h3>3. How We Protect Your Data</h3>
        <p>We take reasonable security measures to protect your personal data from unauthorized access, modification, or
            destruction. Data is securely stored on servers and can only be accessed by authorized users
            (administrators).</p>

        <h3>4. Sharing Data</h3>
        <p>We will not share your personal data with third parties unless required by law or to protect our legal
            rights. We do not sell or lease your data to any other parties.</p>

        <h3>5. Your Rights</h3>
        <ul>
            <li>You can access your personal data at any time through the app.</li>
            <li>You can request to correct or delete your personal data by contacting us at <a
                    href="mailto:hr@tadafuq.ae">hr@tadafuq.ae</a>.</li>
        </ul>

        <h3>6. Changes to the Privacy Policy</h3>
        <p>We may update this privacy policy from time to time. We will post updates on this page and clarify the date
            of the last update.</p>

        <h3>7. Contact Us</h3>
        <p>If you have any questions about this privacy policy, you can contact us via:</p>
        <ul>
            <li>Email: <a href="mailto:hr@tadafuq.ae">hr@tadafuq.ae</a></li>
            <li>Web: <a href="http://www.tadafuq.ae" target="_blank">www.tadafuq.ae</a></li>
        </ul>
    </div>
</body>

</html>